【タグ】タグを削除したら関連テーブルの内容も削除する #307
portal-dots/PortalDots pull request #308
Opened 2020-08-23 17:13 UTC by SofPyon

**マイグレーション必要**

## 実装内容
close #307

- タグ一覧から削除ボタンを押すと、確認画面が表示されるようにしました
    - 確認画面には注意事項が記載されています
- タグを削除すると、circle_tag、page_viewable_tags、form_answerable_tagsからも削除されるようにしました
    - 企画、お知らせ、フォーム自体は削除されません

## 懸念点

## レビュワーに見て欲しい点
- マイグレーションが正常に動作するか
- タグを削除すると、 tag_id と紐付けられているレコードが削除されるか
- 余計なものが削除されないか・削除されるべきものが削除されるか

## 参考URL

2020-08-25 10:29 UTC, SofPyon commented
@hosakou 
タグ名を変更すると、企画etcとの紐付けが解除されてしまうバグを発見してしまったので、いったんレビュー保留でお願いします、、

2020-08-26 13:23 UTC, SofPyon commented
@hosakou 
修正完了したのでレビューお願いしたいです！

タグ名を変更すると企画との紐付けが解除されてしまう件、Grocery CRUDのバグっぽかったので、タグ編集画面を v2 化してみました。

2020-08-31 05:21 UTC, hosakou commented
@SofPyon 
試験等あったので遅くなってしまいました！
今週中にはレビューします！

2020-09-03 08:57 UTC, hosakou requested changes
@SofPyon 
データベースにちゃんと反映されました！
タグの削除で関連したテーブルから紐付けが削除されていることも確認しました！
紐付けがなくなった申請・お知らせが全体に公開されることも確認できました！

タグとは関係ないところですが1点だけお願いします

2020-09-03 08:57 UTC, hosakou commented on public/assets/grocery_crud/themes/crud-bootstrap/views/list.php
> +					<?php }?>
「エディターで編集」ボタンが 53行目 にも存在しているようです！

↓ 申請管理
![image](https://user-images.githubusercontent.com/8391342/92091175-5537e980-ee0b-11ea-8bd8-ebe8ba90b4a4.png)

2020-09-13 09:44 UTC, SofPyon commented
@hosakou 
遅くなって申し訳ない！明日までに修正します

-----

忘れないうちにメモ

- 本番環境でマイグレーションを実行すると、idの整合性が合わなくてエラーになってしまうかも…？
    - id = 1 のお知らせ(pages と viewable_page_tags)を削除した上でマイグレーションを実行したほうがよさそう？

2020-09-14 13:32 UTC, SofPyon commented
@hosakou 
修正しました！

![image](https://user-images.githubusercontent.com/6687653/93092270-2eff2d00-f6da-11ea-8140-73f8dff2f1a1.png)

2020-09-17 08:06 UTC, hosakou approved these changes
@SofPyon 
修正確認しました！

>本番環境でマイグレーションを実行すると、idの整合性が合わなくてエラーになってしまうかも…？
id = 1 のお知らせ(pages と viewable_page_tags)を削除した上でマイグレーションを実行したほうがよさそう？

了解です！念の為アップデート前に削除しておきます！

2020-09-17 08:07 UTC, merged