【インストーラー】noindexをつける #408
portal-dots/PortalDots pull request #547
Opened 2021-04-13 15:23 UTC by SofPyon

## 実装内容
close #408

- インストーラーの全ページに noindex をつけるようにしました

## 懸念点

## レビュワーに見て欲しい点
インストーラーの全ページに `<meta name="robots" content="noindex">` が書かれているか。

## 参考URL

2021-04-30 14:25 UTC, hosakou requested changes
@SofPyon 
動作チェック等行いました！

3つだけ確認お願いします！

2021-04-30 14:25 UTC, hosakou commented on routes/staff.php
> +                ;
TODO のコメントと L112 の `;` は消し忘れですかね？

2021-04-30 14:25 UTC, hosakou commented on resources/views/staff/circles/index.blade.php
> +            </a>
カスタムフォームが存在しないときにエラーが出てしまうみたいです！

![image](https://user-images.githubusercontent.com/8391342/116708176-6670de80-aa0a-11eb-8a54-1924436b03dd.png)

2021-04-30 14:25 UTC, hosakou commented on app/GridMakers/CirclesGridMaker.php
> +                        is_array($item[self::CUSTOM_FORM_QUESTIONS_KEY_PREFIX . $detail->question_id])
以前からそうだったと思うのですが、企画情報一覧に「見出し」が含まれているので今回削除しても良いかもしれませんね！

2021-05-01 03:04 UTC, SofPyon commented
@hosakou 
レビューありがとう！
企画情報一覧に「見出し」が含まれてるの気づいてなかった、、ごめん！

3点とも修正したので確認お願いします！

2021-05-01 12:29 UTC, hosakou approved these changes
@SofPyon 
修正ありがとうございます！

スタッフモード完璧だと思います！

2021-05-01 12:29 UTC, merged