【スタッフ】CSV出力機能 #30
portal-dots/PortalDots pull request #549
Opened 2021-04-14 03:24 UTC by hosakou

## 実装内容
#30 

とりあえず 出力 だけ作成しました！

以下の CSV 出力を Laravel で実装しました
- 場所情報
- 申請の回答
- ユーザー
- お知らせ
- タグ
- スケジュール

## 懸念点
- 企画を複数出力しなければならないところは無理やり感がある

## レビュワーに見て欲しい点
- CSV が問題なくダウンロードできること
- 内容が崩れないこと

## 参考URL

2021-04-17 09:49 UTC, SofPyon requested changes
@hosakou 
実装ありがとう！

これで一通りCSVで出力できるようになっていい感じ、お疲れ様！

以下、数が多くなってしまったんだけど、コメント確認お願いします！

2021-04-17 09:49 UTC, SofPyon commented on app/Exports/AnswersExport.php
> +        foreach ($this->form->questions->sortBy('priority') as $q) {
１） `->sortBy('priority')` はたぶん不要？Question モデルの方で、最初から priority 順になるようにしてるので

https://github.com/portal-dots/PortalDots/blob/89523e50c2680347bd18b1452195f90ce5e686cc/app/Eloquents/Question.php#L57-L64

-----

２）わかりにくいので、変数の命名は `$q` じゃなくて `$question` にしたい！

2021-04-17 09:49 UTC, SofPyon commented on app/Exports/AnswersExport.php
> +            $this->form->questions->sortBy('priority')->pluck('name')->toArray()
ここも `->sortBy('priority')` は不要？

2021-04-17 09:49 UTC, SofPyon commented on app/Exports/CirclesExport.php
> +use App\Eloquents\Form;
この２行は不要？

もしくは、可能ならカスタムフォームの回答を出力できるようにしたい！できそう？

2021-04-17 09:49 UTC, SofPyon commented on app/Exports/CirclesExport.php
> +            $leader ? "{$leader->name}(ID:{$leader->id},{$leader->student_id})" : '',
このフォーマットいいね！

せっかくなので、 `$circle->status_set_by` （登録状況受理設定者）も同じフォーマットで出力したいです！

2021-04-17 09:49 UTC, SofPyon commented on app/Exports/PlacesExport.php
> +            $place->circles->makeHidden('pivot')->toJson(JSON_UNESCAPED_UNICODE),
CSVにJSON含めるのは微妙な気がする、、非情報系の実行委員がみたらなにこれ？ってなりそう

企画一覧のCSVに「使用場所」っていう列があるから、これは不要な気もする。どう思う？

2021-04-17 09:49 UTC, SofPyon commented on app/Exports/TagsExport.php
> +            $tag->circles->makeHidden('pivot')->toJson(JSON_UNESCAPED_UNICODE),
ここに企画一覧のJSONを入れるのは微妙な気もするが、このJSONをやめたら、そもそもタグ一覧をCSVにエクスポートする必要性が薄まる気もする、、

-----

Laravel Excel のドキュメントを調べてみたら、複数の行を一度に return できるらしい。これを利用して、以下のような表にするのもありかな…？こういう表は、かえって分かりづらい？

こうすれば、タグ別に企画を把握できる。タグごとに担当者をつけるときとかに便利かな。
（去年の理大祭みたいに、タグでZoomの個別打ち合わせの日程を分けたい時に便利そう）

![image](https://user-images.githubusercontent.com/6687653/115108288-8f28bb00-9faa-11eb-8f22-51f1861bd168.png)


https://docs.laravel-excel.com/3.1/exports/mapping.html#multiple-rows

![image](https://user-images.githubusercontent.com/6687653/115108031-30af0d00-9fa9-11eb-9f55-6c89ce091856.png)

2021-04-17 09:49 UTC, SofPyon commented on app/Http/Controllers/Staff/Circles/ExportAction.php
>          return Excel::download(new CirclesExport(), "circles_{$now}.csv");
（今回のPRとは関係なくてごめん！）

CSVのファイル名、日本語にしたいです！

というのも、ファイル名が英語だとわかりにくそうなので（特に「企画＝circles」というのはわかりにくそう、、）

企画一覧のCSVなら `企画一覧_2021-04-17_12-34-56.csv` というファイル名にするイメージです。こちらの対応もお願いして良い？
（もしかして、ファイル名を日本語にすると文字化けしてしまう…？）

2021-04-17 09:49 UTC, SofPyon commented on app/Exports/FormsExport.php
> +            $form->questions->sortBy('priority')->makeHidden(['form_id', 'priority'])->toJson(JSON_UNESCAPED_UNICODE),
CSVに設問一覧は入れなくても良い気がする🤔

2021-04-17 09:49 UTC, SofPyon commented on resources/views/staff/tags/index.blade.php
> +                href="{{ route('staff.tags.export') }}"
もし、タグ一覧CSVに企画一覧を↓こういうフォーマットで出力できるようにするなら、ボタンのラベルは「CSVで出力(タグ別企画一覧)」にするとわかりやすくて良さそう

![image](https://user-images.githubusercontent.com/6687653/115108666-aec0e300-9fac-11eb-8f9d-3de4aa26f967.png)

2021-04-17 09:58 UTC, SofPyon commented
@hosakou 

あとごめん！

`Home_staff.php` に、回答一覧のCSVを作成する処理があるんだけど、今回のPRで不要になると思うので、ついでに削除してもらえると嬉しいです！

消すのは以下の２つ？

https://github.com/portal-dots/PortalDots/blob/89523e50c2680347bd18b1452195f90ce5e686cc/application/controllers/Home_staff.php#L356-L358

https://github.com/portal-dots/PortalDots/blob/89523e50c2680347bd18b1452195f90ce5e686cc/application/controllers/Home_staff.php#L371-L455

2021-04-23 14:00 UTC, hosakou commented on app/Exports/PlacesExport.php
> +            $place->circles->makeHidden('pivot')->toJson(JSON_UNESCAPED_UNICODE),
@SofPyon 
場所情報は今後インポート機能を実装するとおもうので場所だけであればわざわざエクスポート機能は使われないと思うんですよね。

2021-04-24 01:44 UTC, SofPyon commented on app/Exports/PlacesExport.php
> +            $place->circles->makeHidden('pivot')->toJson(JSON_UNESCAPED_UNICODE),
＠hosakou
これなんだけど、よくよく考えたら、タグ一覧みたいなCSVにすれば良い気がしてきた

2021-04-26 07:33 UTC, hosakou commented
@SofPyon 
とりあえず修正終わりました！

タグや場所情報の出力では複数行出力に変更しましたが、情報が多いと扱いづらいかなと思い「ID」「企画名」「団体名」しか出力するようにしていません。これ以外の情報も必要であれば出力するようにしますがどうでしょうか

2021-04-26 15:53 UTC, SofPyon requested changes
@hosakou 
修正ありがとう！タグ別・場所別の企画一覧CSVのフォーマットもいい感じです👍

> タグや場所情報の出力では複数行出力に変更しましたが、情報が多いと扱いづらいかなと思い「ID」「企画名」「団体名」しか出力するようにしていません。これ以外の情報も必要であれば出力するようにしますがどうでしょうか

その方針で良いと思います。今後要望があれば対応することにしましょう

一点、実装してもらった企画情報管理のCSV（下段）、チェックボックスの回答が以下のように複数列になってしまう問題がありそうです。申請管理の回答一覧CSV（上段）のように、複数回答も1つの列に収まるようにしたいです！最後、こちらの対応お願いします！🙇‍♂️

![image](https://user-images.githubusercontent.com/6687653/116112072-2fd95200-a6f2-11eb-8e8b-bbd4fd4a5e92.png)

2021-04-26 15:53 UTC, SofPyon commented on tests/Feature/Exports/PlacesExportTest.php
> +use function PHPSTORM_META\map;
これは不要？

2021-04-26 15:53 UTC, SofPyon commented on tests/Feature/Exports/TagsExportTest.php
> +use function PHPSTORM_META\map;
これも不要？

2021-05-01 13:01 UTC, hosakou commented
@SofPyon 
指摘されたもを修正し、少し変更を加えました！

2021-05-01 14:42 UTC, SofPyon approved these changes
@hosakou 
修正ありがとう！
動作問題なさそう、マージします！

2021-05-01 14:42 UTC, merged