【Staff/メール配信】CRONが適切に設定されていない可能性があるとき、アラートを表示する #567
portal-dots/PortalDots pull request #583
Opened 2021-05-03 08:30 UTC by hosakou

## 実装内容
close #567 

- 一番古いメールの `count_failed` と `sent_at` が24時間経過してもセットされていない場合、スタッフモードホームとメール配信設定ページにアラートを表示するようにしました。
## 懸念点

## レビュワーに見て欲しい点

## 参考URL

2021-05-03 11:45 UTC, SofPyon requested changes
@hosakou 
実装ありがとう！
良い感じだと思います。これならメール送信がうまく動いていないかどうか一発でわかりそう

以下確認お願いします！

2021-05-03 11:45 UTC, SofPyon commented on resources/views/staff/home.blade.php
> +        <top-alert type="danger" keep-visible>
↓青い縦の線が揃っていないのが気になるので、 `container-medium` prop を追加したいです！

![image](https://user-images.githubusercontent.com/6687653/116871273-fa32ec80-ac4e-11eb-9ae2-a743b1070305.png)

2021-05-03 11:45 UTC, SofPyon commented on app/Services/Emails/SendEmailService.php
> +     * セットされていない場合に false を返す
コメントで補足すると分かりやすくていいね！

2021-05-03 11:45 UTC, SofPyon commented on app/Http/Controllers/Staff/SendEmails/ListAction.php
>  class ListAction extends Controller
`->with('pages', Page::all());` の削除ありがとう！

ついでですが、今や `ListAction` はリストではないので、アクション名の変更もお願いして良い？？

`SettingsAction` か `IndexAction` あたりが良さげ？

2021-05-06 15:42 UTC, hosakou commented
@SofPyon 
修正しました！
メソッド名はいい感じのものが思い浮かばなかったためそのまま使わせていただきました！

2021-05-08 13:06 UTC, SofPyon approved these changes
@hosakou 
修正ありがとう！！

2021-05-08 13:06 UTC, SofPyon commented on tests/Feature/Services/Emails/SendEmailsServiceTest.php
> +class SendEmailsServiceTest extends TestCase
テスト作成ありがとう！
修正不要ですが、「メールは送信されていないが、配信予約から24時間経過していない場合はtrueを返す」というテストケースがあってもよかったかもです！

2021-05-08 13:06 UTC, merged