【企画参加登録】企画詳細ページに、カスタムフォームの回答内容を表示する #610
portal-dots/PortalDots pull request #721
Opened 2021-08-29 14:36 UTC by SofPyon

## 実装内容
close #issue_number

## 懸念点

## レビュワーに見て欲しい点

## 参考URL

2021-09-27 14:21 UTC, SofPyon commented
UIの変更を含むため、 `4.x` ブランチを作って `4.x` へマージした方が良いかも

2021-10-14 08:36 UTC, hosakou requested changes
@SofPyon 
回答内容が閲覧できることを確認しました！

1点だけ修正お願いします！

2021-10-14 08:36 UTC, hosakou commented on resources/views/includes/question.blade.php
> +        v-bind:disabled="{{ json_encode($is_disabled ?? '' ?? false) }}"
参加登録のフォーム( /circles/create )に `readonly` の属性がついてしまうみたいです
![image](https://user-images.githubusercontent.com/8391342/137280562-93bc7410-7da9-4ee7-b126-14b1117cf79d.png)

2021-10-28 14:00 UTC, SofPyon commented
@hosakou 
確認ありがとう！

> 参加登録のフォーム( /circles/create )に readonly の属性がついてしまうみたいです

こちら修正しました！

---

併せて、マージ先ブランチを `4.x` に変更しました。このPRの修正は PortalDots 4 に入れたいと思います。

2021-11-27 12:42 UTC, merged