【パスワードリセット】ログイン中のユーザーに優しくする #200
portal-dots/PortalDots pull request #748
Opened 2021-09-27 15:47 UTC by kai0310

## 実装内容
close #200

* ログイン中のパスワードを忘れたユーザにパスワードをリセットするページのリンクの追加

## 懸念点

## レビュワーに見て欲しい点

## 参考URL

## TODO
- [x] ログインしないとアクセスできないページ内にある、パスワード入力欄のそばに、「パスワードをお忘れの場合はこちら」というリンクを設置
- [x] ログイン中の場合、パスワードリセットの最初の画面に、予めメールアドレスを入力した状態にしておく
- [ ] （未ログイン時、ログイン画面にメールアドレスが入力された状態で「パスワードをお忘れの場合はこちら」をクリックした場合、そのメールアドレスが入力された状態でパスワードリセット画面を表示したい）

2021-09-27 15:54 UTC, kai0310 commented
>  （未ログイン時、ログイン画面にメールアドレスが入力された状態で「パスワードをお忘れの場合はこちら」をクリックした場合、そのメールアドレスが入力された状態でパスワードリセット画面を表示したい）

こちらPHPで実装できないこともないと思うのですが、JSで行った方が楽そうです. また、以下のことを懸念して実装を行っていません。
* どこに一時的に保存するか
  * session ? localStorage ?
  * 保存する場所によって、メールアドレスという個人情報をどの様に扱うかが変わってくる
* メールアドレスは暗号化せずそのまま平文で保存していいのか

--- 
以上のことを踏まえ、このissueで実装を行うべきかや、その場合の実装方法についてアドバイスしていただきたいです。

2021-09-28 05:26 UTC, SofPyon commented
@kai0310 
Pull Requestの作成ありがとうございます！

> 以上のことを踏まえ、このissueで実装を行うべきかや、その場合の実装方法についてアドバイスしていただきたいです。

上記について、時間があるときに確認します！

2021-09-28 14:50 UTC, SofPyon commented
@kai0310 

>  （未ログイン時、ログイン画面にメールアドレスが入力された状態で「パスワードをお忘れの場合はこちら」をクリックした場合、そのメールアドレスが入力された状態でパスワードリセット画面を表示したい）

こちらですが、この機能を実装することに関する懸念の方が、ユーザー体験向上のメリットを上回っているような気がしてきました。

なので、この機能（ログイン画面に入力されたメールアドレスをパスワードリセット画面で表示する機能）は実装しなくて良いと思います！

2021-09-28 15:07 UTC, SofPyon requested changes
@kai0310 
こちらコードと動作を確認しました！
これでだいぶログイン中のユーザーに優しいUIになった感じがあります！

気になった点として、非ログイン状態でパスワードリセットページにアクセスするとエラーになってしまう問題がありそうなので、こちらの確認をお願いしても良いでしょうか？

2021-09-28 15:07 UTC, SofPyon commented on resources/views/auth/passwords/request.blade.php
> +                           name="login_id" value="{{ old('login_id') ?? auth()->user()->email }}" required autofocus>
非ログイン状態でパスワードリセットページにアクセスすると、エラーになってしまうようです。

こちらエラーが出ないようにしたいです！

![image](https://user-images.githubusercontent.com/6687653/135112399-78c2d5e0-c706-49eb-a380-54ac944b1e9c.png)

2021-09-28 15:07 UTC, SofPyon commented on resources/views/auth/passwords/request.blade.php
> +                    </p>
「パスワードの再設定」ページでは、「パスワードをお忘れの場合はこちら」のリンクは不要だと思います！

![image](https://user-images.githubusercontent.com/6687653/135112842-707da754-a540-4f6c-af42-e3f1bbb2f4d4.png)

2021-09-28 15:07 UTC, SofPyon commented on resources/views/users/change_password.blade.php
> +                    </p>
テキストボックスとリンクの余白が狭い印象がありますね

代わりに、`<template v-slot:label>現在のパスワード</template>` の下に↓このコードを入れれば良い感じのデザインになりそうな気がします。

```html
<template v-slot:description>
    <a href="{{ route('password.request') }}">
        パスワードをお忘れの場合はこちら
    </a>
</template>

2021-09-28 15:07 UTC, SofPyon commented on resources/views/users/edit.blade.php
> +                    </p>
こちらも、テキストボックスとリンクの余白が狭い印象があるので、上記と同様の対応をしたいです！

2022-01-24 09:43 UTC, kai0310 commented
@SofPyon 
遅れました 🙏
レビューお願いします！

2022-02-01 11:27 UTC, SofPyon approved these changes
@kai0310 
レビューが遅れてしまいすみません！
修正ありがとうございました！
問題なさそうですのでマージします。

2022-02-02 14:57 UTC, merged